workflows:
  capacitor-android:
    name: Capacitor Android Release
    instance_type: mac_mini_m2
    environment:
      vars:
        CM_KEYSTORE_REFERENCE: bmi-key
        CM_KEY_ALIAS: upload
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD
    scripts:
      - name: Install deps
        script: npm install
      - name: Build Web
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build AAB
        script: cd android && ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab